# Generated by Django 5.1.7 on 2025-04-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(verbose_name='Descrição do Produto')),
                ('preco', models.FloatField(verbose_name='Preço do Produto')),
                ('estoque', models.IntegerField(default=0, verbose_name='Estoque')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('tamanhos', models.CharField(max_length=255, verbose_name='Tamanhos Disponíveis')),
                ('cores', models.CharField(max_length=255, verbose_name='Cores Disponíveis')),
                ('imagens', models.TextField(verbose_name='URLs das Imagens')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
